### PR TITLE
Use the copied version of external components instead of rails-assets'

### LINKED ISSUE #100: 2.10.0 broken
The latest 2.10.0 release changed expectations for some SCSS files and breaks projects using it because sprockets cannot find, for example 'bootstrap-combobox'. Looking through the recent commit log the change (https://github.com/patternfly/patternfly-sass/commit/7f9fd91d6da86492488583a64b93fb4cbfad6a4e#diff-8dc22444ca25a5fcafa9be7c62b0d8f3L82) was made that moved away from the provided SCSS files for what appears to be existing gems. However, the patternfly-sass gem does not require those gems. I cannot tell if this was intentional or a bug.

### PR DESCRIPTION
**Pull request by skateman**
Fixes #100

### CODE REVIEW

**Comment by skateman** [comment]
@ehelms FYI

**Comment by ehelms** [comment]
Thanks @skateman, I will test this in my environment today and report back.

**Comment by skateman** [comment]
@ehelms there are some issues with bs-touchsping, I'm checking them right now

**Comment by ehelms** [comment]
Basic test of applying and installing a new patternfly gem with this alleviated the issue we were seeing in #100. I did a assets precompile test of our assets as well and everything was OK.

**Comment by skateman** [comment]
great, I found the problem with the touchspin, fix is coming in a few mins & I'll create a maintenance release

**Pull request merged**
