### PR TITLE
Modified converter to be able to convert 2.0.0-rc1

### PR DESCRIPTION
**Pull request by skateman**
Pending issues in the parent project:
* [x] cards https://github.com/patternfly/patternfly/pull/86
* [x] bootstrap-select https://github.com/patternfly/patternfly/pull/87

### CODE REVIEW

**Comment by skateman** [comment]
@awood i've updated only the converter script, so Travis probably will be green, but there are some errors when running `rake convert && rake compile` locally. Can you please take a look at it?

**Comment by himdel** [comment]
@skateman https://github.com/patternfly/patternfly-sass/blob/master/tasks/converter.rb#L125-L126

**Comment by skateman** [comment]
@awood nevermind, problem solved :)

**Comment by skateman** [comment]
Pending issues in the parent project:
* [ ] cards https://github.com/patternfly/patternfly/pull/86
* [ ] bootstrap-select https://github.com/patternfly/patternfly/pull/87

**Pull request merged**
