### PR TITLE
Converted from upstream version 3.14.0

### PR DESCRIPTION
**Pull request by skateman**
@himdel this is for you to play with

### CODE REVIEW

**Comment by himdel** [comment]
No idea what I'm supposed to do with this. Just add package.json and you're probably done. 

What seems to be missing is some line to copy that file, I guess in `tasks/converter.rb#convert`.

**Comment by skateman** [comment]
@himdel for me convert was working, do you have a working `package.json`?

**Comment by himdel** [comment]
Well, https://github.com/patternfly/patternfly/blob/master/package.json, except with `name: "patternfly-sass"`..

**Comment by skateman** [comment]
@himdel will that work 100% sure? :worried:

**Comment by himdel** [comment]
Well, it should work well enough for us to find out what is broken before the next one :)

But maybe also bootstrap -> bootstrap-sass in the dependencies? Depends on whethere patternfly is extending bootstrap's css or overriding the whole thing..

**Pull request merged**
